### ISSUE TITLE
What mating connector cqn I use on the FAN connectors?

### ISSUE THREAD

**Issue by GadgetAngel** [Gi7mo/TinyFan#7]
The FAN connectors on the TinyFan PCB board are PINREX 744-81-04TW20 1x4P.  What mating connector do I buy so I can wire up
my fans?

**Comment by Gi7mo** [comment]
you'll need a general 4 pin pwm fan, that already has the proper connectors
![image](https://user-images.githubusercontent.com/159609/192720500-cca1ea78-c81c-49ed-98af-6901490a040b.png)

**Comment by GadgetAngel** [comment]
I found them at https://modmymods.com/mmm-4-pin-pwm-male-connector-black-mod-0112.html


Here is the female Molex KK crimp connector that should work with the above MMM-4-pin-PWM-Male-Connector: https://www.digikey.com/en/products/detail/molex/0008500113/304071
